version: "3"
services:
    kcptun_client:
        container_name: "kcptun_client_container"
        restart: unless-stopped
        network_mode: "host"
        build:
            context: .
            dockerfile: client.Dockerfile
        image: heawercher/kcptun_client:latest
        command: ["./client", "--version"]

    kcptun_server:
        container_name: "kcptun_server_container"
        restart: unless-stopped
        network_mode: "host"
        build:
            context: .
            dockerfile: server.Dockerfile
        image: heawercher/kcptun_server:latest
        command: ["./server", "--version"]
